import assert from 'node:assert/strict';
import * as THREE from 'three';
import { batchStaticProps } from '../src/engine/StaticMeshBatcher.js';

const root = new THREE.Group();
root.position.set(31, 8, -42);
root.rotation.y = 0.72;
root.scale.setScalar(1.5);
const group = new THREE.Group();
group.position.set(3, 1, 2);
group.rotation.x = 0.3;
root.add(group);
const mat = new THREE.MeshStandardMaterial();
const shared = new THREE.BoxGeometry();
let disposed = false;
shared.addEventListener('dispose', () => disposed = true);
for (let i = 0; i < 5; i++) {
  const mesh = new THREE.Mesh(shared, mat);
  mesh.position.set(i * 2, i, -i);
  mesh.castShadow = true;
  group.add(mesh);
}
const excluded = new THREE.Group();
excluded.add(new THREE.Mesh(shared, mat), new THREE.Mesh(shared, mat));
root.add(excluded);
const invisible = new THREE.Group();
invisible.visible = false;
invisible.add(new THREE.Mesh(shared, mat), new THREE.Mesh(shared, mat));
root.add(invisible);
const transparent = new THREE.Mesh(shared, new THREE.MeshBasicMaterial({transparent: true}));
const multiMaterial = new THREE.Mesh(shared, [mat, mat]);
const callback = new THREE.Mesh(shared, mat);
callback.onBeforeRender = () => {};
const mirrored = new THREE.Mesh(shared, mat);
mirrored.scale.x = -1;
root.add(transparent, multiMaterial, callback, mirrored);
root.updateWorldMatrix(true, true);
const before = new THREE.Box3().setFromObject(group, true);
const result = batchStaticProps(root, {exclude: new Set([excluded])});
assert.deepEqual(result, {sourceMeshes: 5, batches: 1, savedMeshes: 4});
const batch = root.children.find(c => c.name === 'StaticBatch_0');
const after = new THREE.Box3().setFromObject(batch, true);
assert.ok(before.min.distanceTo(after.min) < 1e-5);
assert.ok(before.max.distanceTo(after.max) < 1e-5);
assert.equal(batch.geometry.attributes.position.count, 5 * 36);
assert.equal(batch.material, mat);
assert.equal(batch.castShadow, true);
assert.equal(batch.receiveShadow, false);
assert.equal(excluded.children.length, 2);
assert.equal(invisible.children.length, 2);
for (const obj of [transparent, multiMaterial, callback, mirrored]) assert.equal(obj.parent, root);
assert.equal(disposed, false);
assert.deepEqual(batchStaticProps(root, {exclude: new Set([excluded])}), {sourceMeshes: 0, batches: 0, savedMeshes: 0});
console.log('PASS: transforms, geometry, render flags, exclusions, shared resources and idempotence');
